server:
  port: 8761

eureka:
  instance:
    hostname: 121.43.158.100
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
       defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}:${server.port}/eureka/

spring:
  application:
    name: eurake
  security:
    user:
      name: admin
      password: admin

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://121.43.158.100:3306/hyh_project
    username: root
    password: 123456


mybatis-plus:
  mapper-locations: classpath*:mapper/*Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl